### ISSUE TITLE
Changed XML template now it doesn't work

### ISSUE THREAD

**Issue by Bluesguy1984** [jpsfs/TFSScrumExtensions#7]
I have been using this extension for a while and I had just changed my XML template and when I tried to do the Plan Work Item I got an error message.  Foolishly I told it to not show me the error again :-(

I have **uninstalled** TFSScrumExtensions and **reinstalled** it but I never get the Plan Work Item.  I have tried to find the XML file the extension is using, without success.

What do I do?

**Comment by Bluesguy1984** [comment]
Additional Info

----- Catalog construction errors -----
Error #1
Microsoft.VisualStudio.Composition.PartDiscoveryException: Unable to load assembly "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\3TNTKK0T.C2F\TFSScrumExtensions.dll" for scanning. ---> System.IO.FileNotFoundException: Could not load file or assembly 'TFSScrumExtensions.dll' or one of its dependencies. The system cannot find the path specified. ---> System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass11_0.<CreatePartsAsync>b__0(String path)
   --- End of inner exception stack trace ---

**Comment by Bluesguy1984** [comment]
I have also cleared out the registry with any reference to this component and rebooted

**Comment by jpsfs** [comment]
Hi!

Thank you for getting in touch.
This extension is a bit unsupported for some time but soon there should be an update to address the issue you described an support Visual Studio 2017 also.

In any case, the error you are facing now seems to be related with the extension installation, probably due to the uninstall/install process. It's quite common for thinks to go sideways on this process with any Visual Studio extension. Microsoft's advice for this is to clean the Visual Studio MEF cache, you can find an extension to help you do that here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

Please let me know if that fixes the problem for you.

Best,
José

**Comment by jpsfs** [comment]
Btw, the location of the XML file to update is:
C:\Users\<user>\AppData\Roaming\TFSScrumExtensions

Best,
José

**Comment by Bluesguy1984** [comment]
Turns out if you delete the default file, run the Clear MEF Component Cache and uninstall and reinstall TFSScrumExtensions everything starts to work again :-)... Very happy.

Thank you!
